/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BaseType {
  id: Generated<string>;
  inserted_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Races extends BaseType {
  status: string; // upcoming, live, finished
  race_number: Numeric;
  start_time: Timestamp | null;
  racer_ids: string;
  results: Json;
  racer_winner_id: string | null;
  race_protocol_id: string | null;
  race_creation_txn_id: string | null;
  payout_txn_id: string | null;
}

export interface Racers extends BaseType {
  name: string;
  number: Numeric;
  color: string;
  odds: Numeric;
  allow_bet: boolean;
  image_url: string;
}

export interface Admin extends BaseType {
  wallet_address: string;
}

export interface DB {
  nochill_races: Races;
  nochill_racers: Racers;
  nochill_admin: Admin;
}
